@host=http://127.0.0.1:3000
@content=application/json
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJndWd1biIsImVtYWlsIjoiZ3VndW5AZ21haWwuY29tIiwiaWF0IjoxNzU3NzM2ODU3LCJleHAiOjE3NTc3NDA0NTd9.Nu5i_Ps8S1Bg_4btcrSgnKlLP7Tuh4tnXw_WcAcCtSM

### Get All Products (Public)
GET {{host}}/products/all HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{content}}

### Get Product By ID (Public)
GET {{host}}/products/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{content}}

### Create Product (Protected)
POST {{host}}/products/create HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{content}}

{
    "name": "Product Test",
    "description": "This is a test product",
    "image_url": "http://example.com/image.jpg",
    "price": 100000,
    "category_id": 1
}



